### ISSUE TITLE
Error: attempt to index upvalue 'nodemon'

### ISSUE THREAD

**Issue by kstrabala** [timn/roslua#1]
Hey Tim,

I'm getting this error from skiller when I send commands from skillgui and luaagent.  Does this look like something in your code?  Could it be related to a problem/error we are having with the right hand?

Kyle

Lua runtime error in pcall: [string "/pr/intel-pkg/system/behavior_engine/skille..."]:139: attempt to index upvalue 'nodemon' (a nil value)
stack traceback:
        [string "/pr/intel-pkg/system/behavior_engine/skille..."]:139: in function 'cancel_cb'
        [string "/pr/intel-pkg/system/behavior_engine/action..."]:321: in function 'cancel_goals_before'
        [string "/pr/intel-pkg/system/behavior_engine/skille..."]:60: in function 'goal_cb'
        [string "/pr/intel-pkg/system/behavior_engine/action..."]:266: in function <[string "/pr/intel-pkg/system/behavior_engine/action..."]:251>
        (tail call): ?
        [string "/pr/intel-pkg/system/roslua/src/roslua/subs..."]:102: in function 'dispatch'
        [string "/pr/intel-pkg/system/roslua/src/roslua/subs..."]:284: in function 'spin'
        /pr/intel-pkg/system/roslua/src/roslua/init.lua:344: in function </pr/intel-pkg/system/roslua/src/roslua/init.lua:332>

**Comment by timn** [comment]
That is a snippet regarding our node monitoring code, which tries to report the error with the right hand. I'm looking at it right now to fix it, it's probably missing a guard.

**Comment by timn** [comment]
It's actually a skiller issue, not a roslua issue... Fixed in latest push.
